/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * v5.18.0 — Auto-Generate Recommended Shifts.
 *
 * Reads station hourly demand profiles + the company's operating window and
 * emits a set of Shift records sized to cover demand while keeping every
 * generated shift inside `config.standardDailyHrsCap` (so the auto-scheduler
 * doesn't have to fall back to OT for routine coverage). The output is
 * additive — generated shifts carry `autoGenerated: true` so ShiftsTab can
 * surface them with a distinct chip and the supervisor can edit / remove
 * them without touching the hand-authored library.
 *
 * Algorithm (kept deterministic + explainable, not optimal):
 *   1. Sum required HC across every open station for each hour 0–23,
 *      separately for normal and peak day types. The peak profile drives
 *      shift start/end placement (worst-case sizing) — normal-day under-
 *      staffing is a separate choice for the auto-scheduler, not the
 *      generator.
 *   2. Scan the peak profile for contiguous "open windows" — runs of hours
 *      where peak HC > 0. Multiple disjoint windows mean disjoint shift
 *      sets (covering e.g. an early-morning prep window separate from a
 *      late-evening service window).
 *   3. For each window, length L vs daily cap C:
 *        L ≤ C        → 1 anchor shift covering the whole window.
 *        L ≤ 2C       → 2 staggered shifts: opener [start, start+C] and
 *                       closer [end-C, end]; they overlap mid-window which
 *                       is intentional (peak HC tends to live there).
 *        L > 2C       → 3 shifts: opener / mid / closer. The mid shift is
 *                       centred within the window, length C.
 *   4. Each generated shift's recommended HC is `max(peakProfile[h])` for
 *      hours it covers. The supervisor staffs to that number; the auto-
 *      scheduler then assigns employees ≤ daily cap.
 *
 * Why this is the "least OT / least liabilities" pick:
 *   - Every generated shift has duration ≤ daily cap, so any single
 *     assignment stays under Art. 67 / Art. 88 daily limits.
 *   - Overlapping coverage at peak hours means the auto-scheduler can
 *     spread the peak HC across two staggered shifts instead of stacking
 *     a single shift's headcount, which reduces consecutive-day strain
 *     (Art. 71 rest gap easier to satisfy).
 *   - No generated shift crosses midnight — keeps holiday-day attribution
 *     unambiguous (Art. 74 comp / cash decisions are date-based).
 *
 * Limitations / out-of-scope:
 *   - Doesn't generate hazardous or industrial-rotating flagged shifts —
 *     those are policy decisions the supervisor must own.
 *   - Doesn't second-guess the company operating window: if shopOpening/
 *     Closing are wrong, the demand windows will be wrong too. The
 *     generator surfaces a `notes` entry when it suspects this.
 *   - Doesn't account for break-min preferences beyond a default 60 min
 *     break for shifts ≥ 6h. The user can edit any generated shift to
 *     refine.
 */

import type { Shift, Station, Config } from '../types';
import { getRequiredHC } from './stationDemand';
import { computeCoverageProfile, findCoverageGaps, summarizeCoverage, type CoverageProfile } from './shiftCoverage';

export interface ShiftSuggestion {
  shift: Shift;
  // Maximum required headcount across the hours this shift spans, per day type.
  recommendedNormalHC: number;
  recommendedPeakHC: number;
  // The hour-range this shift is intended to staff — useful for the preview UI
  // even though the same span is encoded in `shift.start` / `shift.end`.
  spanHours: number;
}

// v5.19.0 — verdict the generator emits about the existing shift library:
//   'adequate'   — every demand hour is already covered by an existing
//                  work shift; the generator emits 0 new shifts.
//   'partial'    — some demand hours are covered, others are gaps; the
//                  generator only emits shifts to fill the gap windows.
//   'no-coverage'— no existing work shift covers ANY demand hour; the
//                  generator runs in its v5.18 unrestricted mode and
//                  emits a full set sized to the whole demand profile.
//   'no-demand'  — there's no demand profile at all (caller hasn't set
//                  station HC); 0 generated.
export type CoverageVerdict = 'adequate' | 'partial' | 'no-coverage' | 'no-demand';

export interface GenerationResult {
  // Newly-generated Shift records, ready to merge into the company's shift
  // library. All carry `autoGenerated: true` and have unique codes that
  // don't collide with `existingShifts`.
  generated: Shift[];
  // Same shifts paired with recommended HC + span metadata for the preview UI.
  suggestions: ShiftSuggestion[];
  // Hour-by-hour demand profile (24 entries) that fed the generator. The
  // preview UI plots this as a sparkline so the supervisor can see what
  // the generator was working from.
  demandProfile: {
    normalByHour: number[];
    peakByHour: number[];
  };
  // Plain-language notes explaining edge cases the generator hit
  // (e.g. "no demand detected", "windows merged"). Surfaced in the
  // preview modal as a bullet list.
  notes: string[];
  // v5.19.0 — coverage telemetry. The verdict is the headline; the
  // numbers below let the UI phrase it precisely ("12 of 14 demand
  // hours covered, 2 gaps remaining"). `existingCoverage` reflects
  // the state BEFORE the generator's output is applied — supervisors
  // see what their current shift library does on its own.
  verdict: CoverageVerdict;
  existingCoverage: {
    totalDemandHours: number;
    coveredHours: number;
    uncoveredHours: number;
    pctCovered: number;
  };
  // Demand windows the generator detected (peak HC > 0 contiguous runs).
  // The UI uses these to show "your venue's busy windows are 11–15 and
  // 17–23" alongside the gap analysis.
  demandWindows: Array<{ start: number; end: number }>;
  // The covering work shifts already in the library (excluding system
  // shifts). Surfaced so the UI can name them when explaining the
  // adequate verdict.
  coveringShifts: CoverageProfile['coveringShifts'];
  // v5.19.1 — shift-quality issues detected on the existing library. The
  // gap-detection logic only checks "every demand hour has at least one
  // shift on the floor", which can return adequate=true for a library
  // that is technically covering but operationally bad — e.g. a single
  // 12-hour shift that violates Art. 67's 8-hour daily cap, or two
  // shifts both spanning the entire window where one obsoletes the
  // other. These issues are surfaced in the preview banner so
  // supervisors don't read "adequate" as "no action needed".
  existingIssues: ExistingIssue[];
}

// v5.19.1 — quality issue detected on a shift currently in the library.
//   'over-cap'  : duration > config.standardDailyHrsCap (Art. 67 risk).
//                 The auto-scheduler will refuse to assign anyone to it
//                 at level 1 / 2; only Level 3 (emergency) accepts.
//   'redundant' : another work shift with identical hours + flags
//                 already exists. The auto-scheduler picks one or the
//                 other arbitrarily; supervisors should consolidate.
//   'subsumed'  : a shorter shift is fully inside a longer one (same
//                 flags). The longer shift covers the same span; the
//                 shorter is obsolete unless deliberately kept for a
//                 break-time / preference difference.
export interface ExistingIssue {
  kind: 'over-cap' | 'redundant' | 'subsumed';
  shiftCode: string;
  shiftName: string;
  // For redundant / subsumed, the OTHER shift involved.
  otherCode?: string;
  message: string;
}

const SAFE_DAILY_CAP_FALLBACK = 8;

export function generateOptimalShifts(
  stations: Station[],
  config: Config,
  existingShifts: Shift[],
): GenerationResult {
  const dailyCap = clampInt(config.standardDailyHrsCap || SAFE_DAILY_CAP_FALLBACK, 2, 12);

  const normalByHour = new Array(24).fill(0) as number[];
  const peakByHour = new Array(24).fill(0) as number[];
  const notes: string[] = [];

  for (const st of stations) {
    const stOpen = parseHourFloor(st.openingTime);
    const stClose = parseHourCeil(st.closingTime);
    if (stClose <= stOpen) continue;
    for (let h = stOpen; h < stClose && h < 24; h++) {
      normalByHour[h] += getRequiredHC(st, h, false);
      // v5.18.0 — for sizing, use max(peak, holiday). Holiday-tier demand
      // typically spikes above peak (festival surge); generated shifts
      // need to cover whichever is highest so the auto-scheduler can
      // staff both day types from the same shift library. When the
      // station has no holiday-tier override `getRequiredHC(_, _, true)`
      // falls through to peak, so this max() is a no-op there.
      const peakHC = getRequiredHC(st, h, true);
      const holidayHC = getRequiredHC(st, h, false, true);
      peakByHour[h] += Math.max(peakHC, holidayHC);
    }
  }

  const totalPeakDemand = peakByHour.reduce((a, b) => a + b, 0);
  const profile = computeCoverageProfile(existingShifts);
  // v5.19.1 — detect quality issues on existing shifts BEFORE the
  // gap analysis. Surfaced regardless of verdict so adequate-coverage
  // libraries that are nonetheless inefficient still get flagged.
  const existingIssues = detectExistingIssues(existingShifts, dailyCap);
  if (totalPeakDemand === 0) {
    notes.push('no-demand');
    return {
      generated: [],
      suggestions: [],
      demandProfile: { normalByHour, peakByHour },
      notes,
      verdict: 'no-demand',
      existingCoverage: { totalDemandHours: 0, coveredHours: 0, uncoveredHours: 0, pctCovered: 100 },
      demandWindows: [],
      coveringShifts: profile.coveringShifts,
      existingIssues,
    };
  }

  const windows = findOpenWindows(peakByHour);
  const existingCoverage = summarizeCoverage(windows, profile);

  // v5.19.0 — gap-aware proposal building. Walk each demand window,
  // detect the SUB-windows not yet covered by existing work shifts,
  // and only build shifts for those gaps. If a window is fully
  // covered the inner loop emits 0 proposals; if a window is fully
  // uncovered we get the v5.18 behaviour (one-shift / open+close /
  // open+mid+close depending on length). Mid-window partial coverage
  // produces multiple smaller proposals — one per gap.
  const generated: Shift[] = [];
  const suggestions: ShiftSuggestion[] = [];
  const usedCodes = new Set(existingShifts.map(s => s.code.toUpperCase()));
  let counter = 1;
  const nextCode = (): string => {
    let code: string;
    do {
      code = `AG${counter++}`;
    } while (usedCodes.has(code.toUpperCase()));
    usedCodes.add(code.toUpperCase());
    return code;
  };

  for (const win of windows) {
    const gaps = findCoverageGaps(win.start, win.end, profile);
    if (gaps.length === 0) {
      // Window is fully covered by existing shifts — skip.
      continue;
    }

    for (const gap of gaps) {
      const span = gap.end - gap.start;
      if (span <= 0) continue;

      const proposals: Array<{ start: number; end: number; label: 'open' | 'anchor' | 'mid' | 'close' }> = [];
      if (span <= dailyCap) {
        proposals.push({ start: gap.start, end: gap.end, label: 'anchor' });
      } else if (span <= dailyCap * 2) {
        proposals.push({ start: gap.start, end: gap.start + dailyCap, label: 'open' });
        proposals.push({ start: gap.end - dailyCap, end: gap.end, label: 'close' });
      } else {
        const openerEnd = gap.start + dailyCap;
        const closerStart = gap.end - dailyCap;
        const midCentre = Math.round((gap.start + gap.end) / 2);
        const midStart = clampInt(midCentre - Math.floor(dailyCap / 2), openerEnd - 1, closerStart + 1);
        const midEnd = clampInt(midStart + dailyCap, midStart + 1, gap.end);
        proposals.push({ start: gap.start, end: openerEnd, label: 'open' });
        proposals.push({ start: midStart, end: midEnd, label: 'mid' });
        proposals.push({ start: closerStart, end: gap.end, label: 'close' });
        notes.push('long-window');
      }

      for (const p of proposals) {
        const peakHC = maxInRange(peakByHour, p.start, p.end);
        const normalHC = maxInRange(normalByHour, p.start, p.end);
        const startTime = formatHour(p.start);
        const endTime = formatHour(p.end);
        const duration = p.end - p.start;
        const code = nextCode();
        const shift: Shift = {
          code,
          name: `Auto · ${labelFor(p.label)} ${startTime}–${endTime}`,
          start: startTime,
          end: endTime,
          durationHrs: duration,
          breakMin: duration >= 6 ? 60 : 0,
          isIndustrial: false,
          isHazardous: false,
          isWork: true,
          description: `Auto-generated to cover ${normalHC} PAX (normal) / ${peakHC} PAX (peak) between ${startTime} and ${endTime}. Edit to refine — saving converts it to a regular shift.`,
          autoGenerated: true,
        };
        generated.push(shift);
        suggestions.push({
          shift,
          recommendedNormalHC: normalHC,
          recommendedPeakHC: peakHC,
          spanHours: duration,
        });
      }
    }
  }

  // Verdict — the reason the generator emitted what it did. Drives the
  // preview UI's headline ("Existing setup is adequate" vs "Adding 2
  // shifts to fill the 19:00–23:00 gap").
  let verdict: CoverageVerdict;
  if (existingCoverage.totalDemandHours === 0) {
    verdict = 'no-demand';
  } else if (existingCoverage.uncoveredHours === 0) {
    verdict = 'adequate';
    notes.push('adequate-coverage');
  } else if (existingCoverage.coveredHours === 0) {
    verdict = 'no-coverage';
  } else {
    verdict = 'partial';
    notes.push('partial-coverage');
  }

  return {
    generated,
    suggestions,
    demandProfile: { normalByHour, peakByHour },
    notes,
    verdict,
    existingCoverage,
    demandWindows: windows,
    coveringShifts: profile.coveringShifts,
    existingIssues,
  };
}

// v5.19.1 — quality scan over the existing shift library. Catches three
// classes of issue the gap-coverage check misses:
//   1. Any work shift > daily cap.
//   2. Two work shifts with identical (start, end, flags) — redundant.
//   3. A shorter shift fully inside a longer one with same flags — subsumed.
// Issues are reported even when the gap-coverage verdict is 'adequate'
// because covering all hours doesn't mean the library is efficient.
function detectExistingIssues(shifts: Shift[], dailyCap: number): ExistingIssue[] {
  const out: ExistingIssue[] = [];
  type Parsed = { shift: Shift; startHour: number; endHour: number; durationHrs: number };
  const parsed: Parsed[] = [];
  for (const sh of shifts) {
    if (!sh.isWork) continue;
    if (isSystemWork(sh.code)) continue;
    const startHour = parseHourFloor(sh.start);
    const endHour = parseHourCeil(sh.end);
    if (!Number.isFinite(startHour) || !Number.isFinite(endHour)) continue;
    if (endHour <= startHour) continue;
    const durationHrs = endHour - startHour;
    parsed.push({ shift: sh, startHour, endHour, durationHrs });
    if (durationHrs > dailyCap) {
      out.push({
        kind: 'over-cap',
        shiftCode: sh.code,
        shiftName: sh.name,
        message: `${sh.code} runs ${durationHrs}h (${sh.start}–${sh.end}) — exceeds the ${dailyCap}h daily cap. The auto-scheduler will skip it at strict levels and only assign at emergency level. Split into two staggered shifts.`,
      });
    }
  }

  // Pairwise redundant + subsumed checks — N² but N is typically <10.
  // Sort longest first so a "subsumed by" relationship reports the shorter
  // shift as the issue.
  parsed.sort((a, b) => b.durationHrs - a.durationHrs);
  const flagged = new Set<string>();
  const pairKey = (a: string, b: string) => a < b ? `${a}|${b}` : `${b}|${a}`;
  for (let i = 0; i < parsed.length; i++) {
    for (let j = i + 1; j < parsed.length; j++) {
      const a = parsed[i];
      const b = parsed[j];
      if (a.shift.isHazardous !== b.shift.isHazardous) continue;
      if (a.shift.isIndustrial !== b.shift.isIndustrial) continue;
      const k = pairKey(a.shift.code, b.shift.code);
      if (flagged.has(k)) continue;

      // Identical window → redundant. Flag the shorter shift name (or
      // the second-encountered if equal length).
      if (a.startHour === b.startHour && a.endHour === b.endHour) {
        out.push({
          kind: 'redundant',
          shiftCode: b.shift.code,
          shiftName: b.shift.name,
          otherCode: a.shift.code,
          message: `${b.shift.code} (${b.shift.start}–${b.shift.end}) has the same window and flags as ${a.shift.code}. The auto-scheduler treats them interchangeably; consolidate.`,
        });
        flagged.add(k);
        continue;
      }
      // b fully inside a → subsumed.
      if (b.startHour >= a.startHour && b.endHour <= a.endHour) {
        out.push({
          kind: 'subsumed',
          shiftCode: b.shift.code,
          shiftName: b.shift.name,
          otherCode: a.shift.code,
          message: `${b.shift.code} (${b.shift.start}–${b.shift.end}, ${b.durationHrs}h) is fully covered by the longer ${a.shift.code} (${a.shift.start}–${a.shift.end}, ${a.durationHrs}h). Keep only if the break or preference differs; otherwise the longer shift covers this window already.`,
        });
        flagged.add(k);
      }
    }
  }
  return out;
}

// Local copy of isSystemShift so this module doesn't grow a dependency on
// systemShifts.ts (the helper is already inlined in shiftCoverage.ts).
const SYSTEM_CODES = new Set(['OFF', 'AL', 'SL', 'MAT', 'PH', 'CP']);
function isSystemWork(code: string): boolean { return SYSTEM_CODES.has(code); }

function findOpenWindows(profile: number[]): Array<{ start: number; end: number }> {
  const windows: Array<{ start: number; end: number }> = [];
  let cur = -1;
  for (let h = 0; h < 24; h++) {
    if (profile[h] > 0) {
      if (cur === -1) cur = h;
    } else if (cur !== -1) {
      windows.push({ start: cur, end: h });
      cur = -1;
    }
  }
  if (cur !== -1) windows.push({ start: cur, end: 24 });
  return windows;
}

function labelFor(label: 'open' | 'anchor' | 'mid' | 'close'): string {
  switch (label) {
    case 'open': return 'Open';
    case 'mid': return 'Mid';
    case 'close': return 'Close';
    default: return 'Anchor';
  }
}

function parseHourFloor(hhmm: string | undefined): number {
  if (!hhmm) return 0;
  const [hStr] = hhmm.split(':');
  const h = parseInt(hStr, 10);
  return Number.isFinite(h) ? clampInt(h, 0, 23) : 0;
}

// 23:59 → 24 (end-of-day), 23:00 → 23, 12:30 → 13 (round up partials).
function parseHourCeil(hhmm: string | undefined): number {
  if (!hhmm) return 24;
  const [hStr, mStr] = hhmm.split(':');
  const h = parseInt(hStr, 10);
  const m = parseInt(mStr, 10) || 0;
  if (!Number.isFinite(h)) return 24;
  if (m > 0) return clampInt(h + 1, 1, 24);
  return clampInt(h, 0, 24);
}

function formatHour(h: number): string {
  if (h >= 24) return '23:59';
  const hh = Math.max(0, Math.min(23, h | 0));
  return `${String(hh).padStart(2, '0')}:00`;
}

function maxInRange(arr: number[], start: number, end: number): number {
  let m = 0;
  for (let h = start; h < end && h < 24; h++) m = Math.max(m, arr[h] || 0);
  return m;
}

function clampInt(n: number, lo: number, hi: number): number {
  const v = Math.round(n);
  if (v < lo) return lo;
  if (v > hi) return hi;
  return v;
}
