/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * v5.18.0 — Auto-Generate Recommended Shifts.
 *
 * Reads station hourly demand profiles + the company's operating window and
 * emits a set of Shift records sized to cover demand while keeping every
 * generated shift inside `config.standardDailyHrsCap` (so the auto-scheduler
 * doesn't have to fall back to OT for routine coverage). The output is
 * additive — generated shifts carry `autoGenerated: true` so ShiftsTab can
 * surface them with a distinct chip and the supervisor can edit / remove
 * them without touching the hand-authored library.
 *
 * Algorithm (kept deterministic + explainable, not optimal):
 *   1. Sum required HC across every open station for each hour 0–23,
 *      separately for normal and peak day types. The peak profile drives
 *      shift start/end placement (worst-case sizing) — normal-day under-
 *      staffing is a separate choice for the auto-scheduler, not the
 *      generator.
 *   2. Scan the peak profile for contiguous "open windows" — runs of hours
 *      where peak HC > 0. Multiple disjoint windows mean disjoint shift
 *      sets (covering e.g. an early-morning prep window separate from a
 *      late-evening service window).
 *   3. For each window, length L vs daily cap C:
 *        L ≤ C        → 1 anchor shift covering the whole window.
 *        L ≤ 2C       → 2 staggered shifts: opener [start, start+C] and
 *                       closer [end-C, end]; they overlap mid-window which
 *                       is intentional (peak HC tends to live there).
 *        L > 2C       → 3 shifts: opener / mid / closer. The mid shift is
 *                       centred within the window, length C.
 *   4. Each generated shift's recommended HC is `max(peakProfile[h])` for
 *      hours it covers. The supervisor staffs to that number; the auto-
 *      scheduler then assigns employees ≤ daily cap.
 *
 * Why this is the "least OT / least liabilities" pick:
 *   - Every generated shift has duration ≤ daily cap, so any single
 *     assignment stays under Art. 67 / Art. 88 daily limits.
 *   - Overlapping coverage at peak hours means the auto-scheduler can
 *     spread the peak HC across two staggered shifts instead of stacking
 *     a single shift's headcount, which reduces consecutive-day strain
 *     (Art. 71 rest gap easier to satisfy).
 *   - No generated shift crosses midnight — keeps holiday-day attribution
 *     unambiguous (Art. 74 comp / cash decisions are date-based).
 *
 * Limitations / out-of-scope:
 *   - Doesn't generate hazardous or industrial-rotating flagged shifts —
 *     those are policy decisions the supervisor must own.
 *   - Doesn't second-guess the company operating window: if shopOpening/
 *     Closing are wrong, the demand windows will be wrong too. The
 *     generator surfaces a `notes` entry when it suspects this.
 *   - Doesn't account for break-min preferences beyond a default 60 min
 *     break for shifts ≥ 6h. The user can edit any generated shift to
 *     refine.
 */

import type { Shift, Station, Config } from '../types';
import { getRequiredHC } from './stationDemand';

export interface ShiftSuggestion {
  shift: Shift;
  // Maximum required headcount across the hours this shift spans, per day type.
  recommendedNormalHC: number;
  recommendedPeakHC: number;
  // The hour-range this shift is intended to staff — useful for the preview UI
  // even though the same span is encoded in `shift.start` / `shift.end`.
  spanHours: number;
}

export interface GenerationResult {
  // Newly-generated Shift records, ready to merge into the company's shift
  // library. All carry `autoGenerated: true` and have unique codes that
  // don't collide with `existingShifts`.
  generated: Shift[];
  // Same shifts paired with recommended HC + span metadata for the preview UI.
  suggestions: ShiftSuggestion[];
  // Hour-by-hour demand profile (24 entries) that fed the generator. The
  // preview UI plots this as a sparkline so the supervisor can see what
  // the generator was working from.
  demandProfile: {
    normalByHour: number[];
    peakByHour: number[];
  };
  // Plain-language notes explaining edge cases the generator hit
  // (e.g. "no demand detected", "windows merged"). Surfaced in the
  // preview modal as a bullet list.
  notes: string[];
}

const SAFE_DAILY_CAP_FALLBACK = 8;

export function generateOptimalShifts(
  stations: Station[],
  config: Config,
  existingShifts: Shift[],
): GenerationResult {
  const dailyCap = clampInt(config.standardDailyHrsCap || SAFE_DAILY_CAP_FALLBACK, 2, 12);

  const normalByHour = new Array(24).fill(0) as number[];
  const peakByHour = new Array(24).fill(0) as number[];
  const notes: string[] = [];

  for (const st of stations) {
    const stOpen = parseHourFloor(st.openingTime);
    const stClose = parseHourCeil(st.closingTime);
    if (stClose <= stOpen) continue;
    for (let h = stOpen; h < stClose && h < 24; h++) {
      normalByHour[h] += getRequiredHC(st, h, false);
      // v5.18.0 — for sizing, use max(peak, holiday). Holiday-tier demand
      // typically spikes above peak (festival surge); generated shifts
      // need to cover whichever is highest so the auto-scheduler can
      // staff both day types from the same shift library. When the
      // station has no holiday-tier override `getRequiredHC(_, _, true)`
      // falls through to peak, so this max() is a no-op there.
      const peakHC = getRequiredHC(st, h, true);
      const holidayHC = getRequiredHC(st, h, false, true);
      peakByHour[h] += Math.max(peakHC, holidayHC);
    }
  }

  const totalPeakDemand = peakByHour.reduce((a, b) => a + b, 0);
  if (totalPeakDemand === 0) {
    notes.push('no-demand');
    return {
      generated: [],
      suggestions: [],
      demandProfile: { normalByHour, peakByHour },
      notes,
    };
  }

  const windows = findOpenWindows(peakByHour);

  const generated: Shift[] = [];
  const suggestions: ShiftSuggestion[] = [];
  const usedCodes = new Set(existingShifts.map(s => s.code.toUpperCase()));
  let counter = 1;
  const nextCode = (): string => {
    let code: string;
    do {
      code = `AG${counter++}`;
    } while (usedCodes.has(code.toUpperCase()));
    usedCodes.add(code.toUpperCase());
    return code;
  };

  for (const win of windows) {
    const span = win.end - win.start;
    const proposals: Array<{ start: number; end: number; label: 'open' | 'anchor' | 'mid' | 'close' }> = [];

    if (span <= dailyCap) {
      proposals.push({ start: win.start, end: win.end, label: 'anchor' });
    } else if (span <= dailyCap * 2) {
      proposals.push({ start: win.start, end: win.start + dailyCap, label: 'open' });
      proposals.push({ start: win.end - dailyCap, end: win.end, label: 'close' });
    } else {
      const openerEnd = win.start + dailyCap;
      const closerStart = win.end - dailyCap;
      const midCentre = Math.round((win.start + win.end) / 2);
      const midStart = clampInt(midCentre - Math.floor(dailyCap / 2), openerEnd - 1, closerStart + 1);
      const midEnd = clampInt(midStart + dailyCap, midStart + 1, win.end);
      proposals.push({ start: win.start, end: openerEnd, label: 'open' });
      proposals.push({ start: midStart, end: midEnd, label: 'mid' });
      proposals.push({ start: closerStart, end: win.end, label: 'close' });
      notes.push('long-window');
    }

    for (const p of proposals) {
      const peakHC = maxInRange(peakByHour, p.start, p.end);
      const normalHC = maxInRange(normalByHour, p.start, p.end);
      const startTime = formatHour(p.start);
      const endTime = formatHour(p.end);
      const duration = p.end - p.start;
      const code = nextCode();
      const shift: Shift = {
        code,
        name: `Auto · ${labelFor(p.label)} ${startTime}–${endTime}`,
        start: startTime,
        end: endTime,
        durationHrs: duration,
        breakMin: duration >= 6 ? 60 : 0,
        isIndustrial: false,
        isHazardous: false,
        isWork: true,
        description: `Auto-generated to cover ${normalHC} PAX (normal) / ${peakHC} PAX (peak) between ${startTime} and ${endTime}. Edit to refine — saving converts it to a regular shift.`,
        autoGenerated: true,
      };
      generated.push(shift);
      suggestions.push({
        shift,
        recommendedNormalHC: normalHC,
        recommendedPeakHC: peakHC,
        spanHours: duration,
      });
    }
  }

  if (generated.length === 0) {
    notes.push('no-demand');
  }

  return {
    generated,
    suggestions,
    demandProfile: { normalByHour, peakByHour },
    notes,
  };
}

function findOpenWindows(profile: number[]): Array<{ start: number; end: number }> {
  const windows: Array<{ start: number; end: number }> = [];
  let cur = -1;
  for (let h = 0; h < 24; h++) {
    if (profile[h] > 0) {
      if (cur === -1) cur = h;
    } else if (cur !== -1) {
      windows.push({ start: cur, end: h });
      cur = -1;
    }
  }
  if (cur !== -1) windows.push({ start: cur, end: 24 });
  return windows;
}

function labelFor(label: 'open' | 'anchor' | 'mid' | 'close'): string {
  switch (label) {
    case 'open': return 'Open';
    case 'mid': return 'Mid';
    case 'close': return 'Close';
    default: return 'Anchor';
  }
}

function parseHourFloor(hhmm: string | undefined): number {
  if (!hhmm) return 0;
  const [hStr] = hhmm.split(':');
  const h = parseInt(hStr, 10);
  return Number.isFinite(h) ? clampInt(h, 0, 23) : 0;
}

// 23:59 → 24 (end-of-day), 23:00 → 23, 12:30 → 13 (round up partials).
function parseHourCeil(hhmm: string | undefined): number {
  if (!hhmm) return 24;
  const [hStr, mStr] = hhmm.split(':');
  const h = parseInt(hStr, 10);
  const m = parseInt(mStr, 10) || 0;
  if (!Number.isFinite(h)) return 24;
  if (m > 0) return clampInt(h + 1, 1, 24);
  return clampInt(h, 0, 24);
}

function formatHour(h: number): string {
  if (h >= 24) return '23:59';
  const hh = Math.max(0, Math.min(23, h | 0));
  return `${String(hh).padStart(2, '0')}:00`;
}

function maxInRange(arr: number[], start: number, end: number): number {
  let m = 0;
  for (let h = start; h < end && h < 24; h++) m = Math.max(m, arr[h] || 0);
  return m;
}

function clampInt(n: number, lo: number, hi: number): number {
  const v = Math.round(n);
  if (v < lo) return lo;
  if (v > hi) return hi;
  return v;
}
