'use strict';

const { app, BrowserWindow, Menu, Tray, nativeImage, shell } = require('electron');
const path = require('path');
const http  = require('http');
const fs    = require('fs');

// ─── Environment ─────────────────────────────────────────────────────────────
const isDev = !app.isPackaged;
const PORT  = 3000;
// Window icon — prefer the multi-size .ico on Windows (sharper at every shell
// context), fall back to the cleaned 256×256 PNG generated by `npm run icons`.
// The original `icon.png` is not used directly because the source file in the
// repo is actually a JPEG mislabeled as .png.
const ICON_ICO = path.join(__dirname, '..', 'assets', 'icon.ico');
const ICON_PNG = path.join(__dirname, '..', 'assets', 'icon-256.png');
const ICON = (process.platform === 'win32' && fs.existsSync(ICON_ICO))
  ? ICON_ICO
  : (fs.existsSync(ICON_PNG) ? ICON_PNG : path.join(__dirname, '..', 'assets', 'icon.png'));

// ─── Data directory ──────────────────────────────────────────────────────────
// Production → AppData\Roaming\IraqiLaborScheduler\data   (writable, persisted)
// Dev        → ./data  (same as the old server.ts behaviour)
const dataDir = isDev
  ? path.join(__dirname, '..', 'data')
  : path.join(app.getPath('userData'), 'data');

if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

process.env.DATA_DIR    = dataDir;
process.env.PORT        = String(PORT);
process.env.NODE_ENV    = isDev ? 'development' : 'production';

// ─── Post-update data snapshot ───────────────────────────────────────────────
// The NSIS installer drops `.update-pending` next to the data folder when an
// update completes. On the next launch we copy `data/` to a timestamped
// `data-backup-<oldVersion>-<timestamp>/` sibling so the user always has a
// rollback point if the new code corrupts state. Rotates: keeps the 5 most
// recent snapshots and prunes the rest.
function performPostUpdateSnapshot() {
  if (isDev) return;
  try {
    const userData = app.getPath('userData');
    // The NSIS installer writes the marker to two candidate folders to defend
    // against name-mismatch (`productName` vs package `name`). Whichever one
    // Electron actually uses for userData wins.
    const candidateMarkers = [
      path.join(userData, '.update-pending'),
      path.join(app.getPath('appData'), 'Iraqi Labor Scheduler', '.update-pending'),
      path.join(app.getPath('appData'), 'iraqi-labor-scheduler', '.update-pending'),
    ];
    const marker = candidateMarkers.find(m => fs.existsSync(m));
    if (!marker) return;

    const lines = fs.readFileSync(marker, 'utf-8').split(/\r?\n/);
    const newVersion = (lines[0] || '').trim() || 'unknown';
    const oldVersion = (lines[1] || '').trim() || 'unknown';
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const backupName = `data-backup-${oldVersion}-${ts}`;
    const backupDir  = path.join(userData, backupName);

    // Defensive copy — if there's no data yet, nothing to back up.
    if (fs.existsSync(dataDir)) {
      try {
        fs.cpSync(dataDir, backupDir, { recursive: true });
        console.log(`[Electron] Pre-${newVersion} data snapshot saved to ${backupDir}`);
      } catch (cpErr) {
        // Don't block startup if the snapshot fails — log only.
        console.error('[Electron] Snapshot copy failed:', cpErr);
      }
    }

    // Rotate: keep the 5 most recent snapshots.
    try {
      const entries = fs.readdirSync(userData, { withFileTypes: true })
        .filter(d => d.isDirectory() && d.name.startsWith('data-backup-'))
        .map(d => ({ name: d.name, full: path.join(userData, d.name), mtime: fs.statSync(path.join(userData, d.name)).mtimeMs }))
        .sort((a, b) => b.mtime - a.mtime);
      for (const old of entries.slice(5)) {
        fs.rmSync(old.full, { recursive: true, force: true });
        console.log(`[Electron] Rotated old snapshot: ${old.name}`);
      }
    } catch (rotErr) {
      console.error('[Electron] Snapshot rotation failed:', rotErr);
    }

    // Stamp the just-applied version so the renderer can show an "Updated to vX" toast.
    process.env.ILS_JUST_UPDATED_FROM = oldVersion;
    process.env.ILS_JUST_UPDATED_TO = newVersion;

    // Clear all candidate markers so the snapshot only happens once per update.
    for (const m of candidateMarkers) {
      try { if (fs.existsSync(m)) fs.unlinkSync(m); } catch { /* best-effort */ }
    }
  } catch (e) {
    console.error('[Electron] Post-update snapshot pipeline failed:', e);
  }
}

performPostUpdateSnapshot();

// ─── Daily auto-snapshot ─────────────────────────────────────────────────────
// Take a copy of the data folder once per calendar day on app launch, so users
// have a recovery point even between version updates. Independent from the
// post-update snapshot above (which only fires after an installer run).
// Retention: keep the 7 most recent daily snapshots — roughly a week of safety.
function performDailySnapshot() {
  if (isDev) return;
  try {
    const userData = app.getPath('userData');
    if (!fs.existsSync(dataDir)) return;
    const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
    const snapshotName = `data-daily-${today}`;
    const snapshotDir = path.join(userData, snapshotName);
    // Idempotent: if today's snapshot already exists, skip. The user's first
    // launch of the day creates it; subsequent launches no-op.
    if (fs.existsSync(snapshotDir)) return;
    try {
      fs.cpSync(dataDir, snapshotDir, { recursive: true });
      console.log(`[Electron] Daily snapshot saved to ${snapshotDir}`);
    } catch (cpErr) {
      console.error('[Electron] Daily snapshot copy failed:', cpErr);
      return;
    }
    // Rotate: keep the 7 most recent daily snapshots.
    try {
      const entries = fs.readdirSync(userData, { withFileTypes: true })
        .filter(d => d.isDirectory() && d.name.startsWith('data-daily-'))
        .map(d => ({ name: d.name, full: path.join(userData, d.name), mtime: fs.statSync(path.join(userData, d.name)).mtimeMs }))
        .sort((a, b) => b.mtime - a.mtime);
      for (const old of entries.slice(7)) {
        fs.rmSync(old.full, { recursive: true, force: true });
        console.log(`[Electron] Rotated old daily snapshot: ${old.name}`);
      }
    } catch (rotErr) {
      console.error('[Electron] Daily snapshot rotation failed:', rotErr);
    }
  } catch (e) {
    console.error('[Electron] Daily snapshot pipeline failed:', e);
  }
}

performDailySnapshot();

// ─── Start Express server in-process (production only) ───────────────────────
// In dev, `npm run dev` already runs the tsx server separately.
if (!isDev) {
  try {
    const serverBundle = path.join(__dirname, '..', 'server-bundle.cjs');
    if (fs.existsSync(serverBundle)) {
      require(serverBundle);
    } else {
      console.error('[Electron] server-bundle.cjs not found at:', serverBundle);
    }
  } catch (e) {
    console.error('[Electron] Failed to start embedded server:', e);
  }
}

// ─── Poll until server is ready ──────────────────────────────────────────────
function waitForServer(cb, retries = 40) {
  const req = http.get(`http://127.0.0.1:${PORT}/api/data`, (res) => {
    res.resume();
    if (res.statusCode < 500) { cb(); return; }
    setTimeout(() => waitForServer(cb, retries - 1), 400);
  });
  req.setTimeout(600);
  req.on('error', () => {
    if (retries > 0) setTimeout(() => waitForServer(cb, retries - 1), 400);
  });
  req.end();
}

// ─── Tray ────────────────────────────────────────────────────────────────────
let tray = null;

function createTray(win) {
  const img = nativeImage.createFromPath(ICON).resize({ width: 16, height: 16 });
  tray = new Tray(img);
  tray.setToolTip('Iraqi Labor Scheduler');
  const menu = Menu.buildFromTemplate([
    { label: 'Open',  click: () => { win.show(); win.focus(); } },
    { type: 'separator' },
    { label: 'Quit',  click: () => { app.isQuitting = true; app.quit(); } },
  ]);
  tray.setContextMenu(menu);
  tray.on('double-click', () => { win.show(); win.focus(); });
}

// ─── Main window ─────────────────────────────────────────────────────────────
let mainWindow = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width:    1440,
    height:   900,
    minWidth: 1100,
    minHeight:700,
    icon:     ICON,
    title:    'Iraqi Labor Scheduler',
    backgroundColor: '#1E293B',
    webPreferences: {
      nodeIntegration:  false,
      contextIsolation: true,
      sandbox:          true,
    },
    show: false,   // reveal once ready-to-show
  });

  // Remove browser menu bar → feels like a native app
  Menu.setApplicationMenu(null);

  const loadURL = () => {
    mainWindow.loadURL(`http://127.0.0.1:${PORT}`);
    mainWindow.once('ready-to-show', () => {
      mainWindow.show();
      if (isDev) mainWindow.webContents.openDevTools({ mode: 'detach' });
    });
  };

  // In dev the server is already running; in prod wait for the embedded server
  if (isDev) {
    waitForServer(loadURL);   // Vite dev server may need a moment too
  } else {
    waitForServer(loadURL);
  }

  // Open external links in the default browser, not in the app window
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });

  // Minimise to tray instead of hiding
  mainWindow.on('minimize', (e) => {
    e.preventDefault();
    mainWindow.hide();
  });

  mainWindow.on('close', (e) => {
    if (!app.isQuitting) {
      e.preventDefault();
      mainWindow.hide();
    }
  });

  mainWindow.on('closed', () => { mainWindow = null; });

  createTray(mainWindow);
}

const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    // Someone tried to run a second instance, we should focus our window.
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      if (!mainWindow.isVisible()) mainWindow.show();
      mainWindow.focus();
    }
  });

  // ─── App lifecycle ────────────────────────────────────────────────────────────
  app.whenReady().then(createWindow);

  app.on('window-all-closed', () => {
    // Don't quit — window is hidden in tray; user must use Tray > Quit
  });

  app.on('activate', () => {
    if (!mainWindow) createWindow();
    else mainWindow.show();
  });

  app.on('before-quit', () => { app.isQuitting = true; });
}
