import React, { useMemo, useState } from 'react';
import { motion } from 'motion/react';
import { X, Sparkles, AlertTriangle, Trash2, ShieldCheck, CheckCircle2, Wand2, ArrowRight, Plus, Minus } from 'lucide-react';
import { Shift, Station, Config } from '../types';
import { generateOptimalShifts } from '../lib/shiftGenerator';
import { buildOptimizationProposal } from '../lib/shiftOptimization';
import { useI18n } from '../lib/i18n';
import { useModalKeys } from '../lib/hooks';
import { cn } from '../lib/utils';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  stations: Station[];
  config: Config;
  existingShifts: Shift[];
  // The user has confirmed the preview — append `generated` to the shift
  // library. App.tsx merges them in (and surfaces the "auto" badge through
  // the autoGenerated flag set on each record).
  onApply: (generated: Shift[]) => void;
  // Number of currently auto-generated shifts in the library — drives the
  // "Clear existing X" action shown in the footer when > 0. Lets the user
  // discard a previous generation pass before applying a new one without
  // hopping back to the table.
  existingAutoCount: number;
  onClearExisting: () => void;
  // v5.19.2 — replace-library action. Removes the supervisor's current
  // work shifts (system shifts CP/OFF/AL/SL/MAT/PH preserved) and
  // appends the proposal. App.tsx wraps this in a confirmation step
  // because it's a wholesale library swap.
  onReplaceLibrary?: (toDelete: Shift[], toAdd: Shift[]) => void;
}

export function AutoGenerateShiftsModal({
  isOpen, onClose, stations, config, existingShifts, onApply, existingAutoCount, onClearExisting,
  onReplaceLibrary,
}: Props) {
  const { t } = useI18n();
  useModalKeys(isOpen, onClose);
  const [confirmingClear, setConfirmingClear] = useState(false);
  // v5.19.2 — two-tab modal:
  //   'gaps'     — fill missing coverage in the existing library (v5.19.0 behaviour)
  //   'optimize' — propose an alternative library built from the demand
  //                profile alone, with one-click adopt-and-replace.
  const [tab, setTab] = useState<'gaps' | 'optimize'>('gaps');

  const result = useMemo(() => {
    if (!isOpen) return null;
    return generateOptimalShifts(stations, config, existingShifts);
  }, [isOpen, stations, config, existingShifts]);

  // Lazy: only build the optimization proposal when the user switches
  // to that tab. Avoids the second generator call on every modal open.
  const proposal = useMemo(() => {
    if (!isOpen || tab !== 'optimize') return null;
    return buildOptimizationProposal(stations, config, existingShifts);
  }, [isOpen, tab, stations, config, existingShifts]);

  if (!isOpen || !result) return null;

  const { generated, suggestions, demandProfile, notes, verdict, existingCoverage, coveringShifts, existingIssues } = result;
  const peakMax = Math.max(1, ...demandProfile.peakByHour);
  const hasNoDemand = verdict === 'no-demand';
  const isAdequate = verdict === 'adequate';
  const isPartial = verdict === 'partial';
  const hasIssues = existingIssues.length > 0;

  const handleApply = () => {
    if (generated.length === 0) {
      onClose();
      return;
    }
    onApply(generated);
    onClose();
  };

  const handleAdopt = () => {
    if (!proposal || !onReplaceLibrary) {
      onClose();
      return;
    }
    onReplaceLibrary(
      proposal.toDelete.map(d => d.shift),
      proposal.toAdd.map(a => a.shift),
    );
    onClose();
  };

  const optimizeUnchanged = proposal
    && proposal.toAdd.length === 0
    && proposal.toDelete.length === 0;

  const handleClearAndClose = () => {
    onClearExisting();
    setConfirmingClear(false);
  };

  return (
    <div className="fixed inset-0 z-[90] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={t('shifts.autoGen.title')}>
      <motion.div
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        className="bg-white dark:bg-slate-900 w-full max-w-3xl rounded-xl shadow-2xl border border-slate-200 dark:border-slate-700 overflow-hidden"
      >
        <div className="p-6 border-b border-slate-100 dark:border-slate-700/60 flex justify-between items-center bg-gradient-to-br from-violet-50 to-blue-50 dark:from-violet-500/10 dark:to-blue-500/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-blue-500 text-white flex items-center justify-center shadow-md">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-800 dark:text-slate-100">{t('shifts.autoGen.title')}</h3>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">{t('shifts.autoGen.subtitle')}</p>
            </div>
          </div>
          <button onClick={onClose} aria-label={t('action.cancel')} className="p-2 hover:bg-slate-200/60 dark:hover:bg-slate-700 rounded-lg transition-colors">
            <X className="w-5 h-5 text-slate-500 dark:text-slate-400" />
          </button>
        </div>

        {/* v5.19.2 — tab nav. "Fill gaps" preserves the original
            v5.19.0 behaviour. "Optimize library" is the new
            prescriptive view that proposes an alternative library
            with a one-click adopt-and-replace action. */}
        {!hasNoDemand && (
          <div className="px-6 pt-4 border-b border-slate-100 dark:border-slate-700/60 flex items-center gap-1">
            <button
              type="button"
              onClick={() => setTab('gaps')}
              className={cn(
                'px-3 py-2 text-[10px] font-black uppercase tracking-widest transition-colors flex items-center gap-1.5',
                tab === 'gaps'
                  ? 'text-violet-700 dark:text-violet-200 border-b-2 border-violet-500'
                  : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 border-b-2 border-transparent',
              )}
            >
              <Sparkles className="w-3 h-3" />
              {t('shifts.autoGen.tab.gaps')}
            </button>
            <button
              type="button"
              onClick={() => setTab('optimize')}
              className={cn(
                'px-3 py-2 text-[10px] font-black uppercase tracking-widest transition-colors flex items-center gap-1.5',
                tab === 'optimize'
                  ? 'text-emerald-700 dark:text-emerald-200 border-b-2 border-emerald-500'
                  : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 border-b-2 border-transparent',
              )}
            >
              <Wand2 className="w-3 h-3" />
              {t('shifts.autoGen.tab.optimize')}
            </button>
          </div>
        )}

        <div className="p-6 space-y-5 max-h-[65vh] overflow-y-auto">
          {hasNoDemand ? (
            <div className="p-5 rounded-lg border border-amber-200 dark:border-amber-500/40 bg-amber-50 dark:bg-amber-500/10 flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-300 shrink-0 mt-0.5" />
              <div className="space-y-1">
                <p className="text-[11px] font-black text-amber-700 dark:text-amber-200 uppercase tracking-widest">{t('shifts.autoGen.noDemand.title')}</p>
                <p className="text-[11px] text-slate-600 dark:text-slate-300 leading-relaxed">{t('shifts.autoGen.noDemand.body')}</p>
              </div>
            </div>
          ) : tab === 'gaps' ? (
            <>
              {/* v5.19.0 — coverage verdict banner. Shown ABOVE the demand
                  chart so the supervisor sees the headline first
                  ("Existing setup is adequate" / "Adding 2 shifts to fill
                  gaps" / "No existing coverage — full plan below"). */}
              <div className={cn(
                'p-4 rounded-lg border flex items-start gap-3',
                isAdequate
                  ? 'border-emerald-200 dark:border-emerald-500/40 bg-emerald-50 dark:bg-emerald-500/10'
                  : isPartial
                    ? 'border-blue-200 dark:border-blue-500/40 bg-blue-50 dark:bg-blue-500/10'
                    : 'border-violet-200 dark:border-violet-500/40 bg-violet-50 dark:bg-violet-500/10',
              )}>
                {isAdequate ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-300 shrink-0 mt-0.5" />
                ) : isPartial ? (
                  <ShieldCheck className="w-5 h-5 text-blue-600 dark:text-blue-300 shrink-0 mt-0.5" />
                ) : (
                  <Sparkles className="w-5 h-5 text-violet-600 dark:text-violet-300 shrink-0 mt-0.5" />
                )}
                <div className="space-y-1.5 min-w-0 flex-1">
                  <p className={cn(
                    'text-[11px] font-black uppercase tracking-widest',
                    isAdequate ? 'text-emerald-700 dark:text-emerald-200'
                    : isPartial ? 'text-blue-700 dark:text-blue-200'
                    : 'text-violet-700 dark:text-violet-200',
                  )}>
                    {isAdequate ? t('shifts.autoGen.verdict.adequate.title')
                    : isPartial ? t('shifts.autoGen.verdict.partial.title', { count: generated.length })
                    : t('shifts.autoGen.verdict.noCoverage.title', { count: generated.length })}
                  </p>
                  <p className="text-[11px] text-slate-700 dark:text-slate-200 leading-relaxed">
                    {isAdequate
                      ? t('shifts.autoGen.verdict.adequate.body', {
                          coverage: existingCoverage.pctCovered,
                          shifts: coveringShifts.map(s => s.code).join(', ') || '—',
                        })
                      : isPartial
                        ? t('shifts.autoGen.verdict.partial.body', {
                            coverage: existingCoverage.pctCovered,
                            uncovered: existingCoverage.uncoveredHours,
                            existing: coveringShifts.map(s => s.code).join(', ') || '—',
                          })
                        : t('shifts.autoGen.verdict.noCoverage.body', {
                            uncovered: existingCoverage.uncoveredHours,
                          })}
                  </p>
                </div>
              </div>

              {/* v5.19.1 — quality issues on the existing library. Surfaced
                  even when verdict is 'adequate' because covering every
                  demand hour doesn't mean the library is efficient
                  (e.g. a 12h shift over the daily cap, two shifts both
                  spanning the same window). */}
              {hasIssues && (
                <div className="p-4 rounded-lg border border-amber-200 dark:border-amber-500/40 bg-amber-50 dark:bg-amber-500/10 space-y-2">
                  <div className="flex items-start gap-2.5">
                    <AlertTriangle className="w-4 h-4 text-amber-700 dark:text-amber-200 shrink-0 mt-0.5" />
                    <div className="min-w-0 flex-1">
                      <p className="text-[11px] font-black text-amber-800 dark:text-amber-200 uppercase tracking-widest">
                        {t('shifts.autoGen.issues.title', { count: existingIssues.length })}
                      </p>
                      <p className="text-[10px] text-amber-700 dark:text-amber-200 leading-relaxed mt-0.5">
                        {t('shifts.autoGen.issues.body')}
                      </p>
                    </div>
                  </div>
                  <ul className="space-y-1.5 ms-6">
                    {existingIssues.map((iss, i) => (
                      <li key={i} className="text-[10px] text-amber-800 dark:text-amber-100 leading-relaxed">
                        <span className="px-1.5 py-0.5 me-1.5 rounded font-mono font-black uppercase tracking-widest text-[8px] bg-amber-100 dark:bg-amber-500/20 border border-amber-200 dark:border-amber-500/40">
                          {t(`shifts.autoGen.issues.kind.${iss.kind}`)}
                        </span>
                        {iss.message}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <div>
                <p className="text-[10px] font-black text-slate-500 dark:text-slate-400 uppercase tracking-widest mb-2">{t('shifts.autoGen.demand.title')}</p>
                <div className="p-3 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/40">
                  <div className="flex items-end gap-px h-24">
                    {demandProfile.peakByHour.map((hc, h) => {
                      const height = (hc / peakMax) * 100;
                      const normal = demandProfile.normalByHour[h];
                      const normalHeight = (normal / peakMax) * 100;
                      return (
                        <div key={h} className="flex-1 flex flex-col justify-end items-stretch relative" title={`${String(h).padStart(2, '0')}:00 — peak ${hc} · normal ${normal}`}>
                          <div
                            className="bg-violet-500/30 dark:bg-violet-400/30 rounded-t-sm"
                            style={{ height: `${height}%` }}
                          />
                          <div
                            className="bg-blue-500 dark:bg-blue-400 absolute bottom-0 inset-x-0 rounded-t-sm"
                            style={{ height: `${normalHeight}%` }}
                          />
                        </div>
                      );
                    })}
                  </div>
                  <div className="flex justify-between mt-1 text-[8px] font-mono text-slate-400 dark:text-slate-500">
                    <span>00</span><span>06</span><span>12</span><span>18</span><span>23</span>
                  </div>
                  <div className="flex items-center gap-3 mt-2 text-[9px] font-bold uppercase tracking-widest">
                    <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-sm bg-blue-500 dark:bg-blue-400" />{t('shifts.autoGen.demand.normal')}</span>
                    <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-sm bg-violet-500/50 dark:bg-violet-400/40" />{t('shifts.autoGen.demand.peak')}</span>
                  </div>
                </div>
              </div>

              {suggestions.length > 0 && (
              <div>
                <p className="text-[10px] font-black text-slate-500 dark:text-slate-400 uppercase tracking-widest mb-2">
                  {t('shifts.autoGen.proposed.title', { count: suggestions.length })}
                </p>
                <div className="space-y-2">
                  {suggestions.map((s) => (
                    <div key={s.shift.code} className="flex items-center gap-3 p-3 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800/40">
                      <div className="px-2 py-1 rounded-md bg-violet-50 dark:bg-violet-500/15 text-violet-700 dark:text-violet-200 border border-violet-200 dark:border-violet-500/40 font-mono text-[10px] font-black tracking-widest">
                        {s.shift.code}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-bold text-slate-800 dark:text-slate-100 truncate">{s.shift.name}</p>
                        <p className="text-[10px] text-slate-500 dark:text-slate-400 font-mono">
                          {s.shift.start}–{s.shift.end} · {s.spanHours}h
                          {s.shift.breakMin > 0 && ` · ${s.shift.breakMin}m ${t('shifts.autoGen.break')}`}
                        </p>
                      </div>
                      <div className="text-end shrink-0">
                        <p className="text-[9px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">{t('shifts.autoGen.recommendedHC')}</p>
                        <p className="text-[10px] font-mono font-bold text-slate-700 dark:text-slate-200">
                          {s.recommendedNormalHC} <span className="text-slate-300 dark:text-slate-600">/</span> <span className="text-violet-600 dark:text-violet-300">{s.recommendedPeakHC}</span>
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              )}

              {notes.includes('long-window') && (
                <div className="p-3 rounded-lg border border-blue-100 dark:border-blue-500/30 bg-blue-50 dark:bg-blue-500/10 text-[10px] text-blue-700 dark:text-blue-200 leading-relaxed">
                  {t('shifts.autoGen.note.longWindow')}
                </div>
              )}
            </>
          ) : (
            // v5.19.2 — Optimize tab: alternative library proposal +
            // side-by-side diff. Surfaced when the supervisor wants
            // the GENERATOR to propose what the library SHOULD look
            // like, not just patch the gaps in what's there.
            proposal && (
              <OptimizeView proposal={proposal} unchanged={!!optimizeUnchanged} />
            )
          )}

          {existingAutoCount > 0 && (
            <div className="p-3 rounded-lg border border-rose-100 dark:border-rose-500/30 bg-rose-50 dark:bg-rose-500/10">
              <p className="text-[10px] font-black text-rose-700 dark:text-rose-200 uppercase tracking-widest mb-1">
                {t('shifts.autoGen.existing.title', { count: existingAutoCount })}
              </p>
              <p className="text-[10px] text-slate-600 dark:text-slate-300 leading-relaxed mb-2">{t('shifts.autoGen.existing.body')}</p>
              {confirmingClear ? (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleClearAndClose}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-rose-600 text-white rounded-md text-[10px] font-black uppercase tracking-widest hover:bg-rose-700 transition-colors"
                  >
                    <Trash2 className="w-3 h-3" />
                    {t('shifts.autoGen.existing.confirmClear')}
                  </button>
                  <button
                    type="button"
                    onClick={() => setConfirmingClear(false)}
                    className="px-3 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 rounded-md text-[10px] font-bold uppercase tracking-widest hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
                  >
                    {t('action.cancel')}
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => setConfirmingClear(true)}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-white dark:bg-slate-900 border border-rose-200 dark:border-rose-500/40 text-rose-700 dark:text-rose-200 rounded-md text-[10px] font-bold uppercase tracking-widest hover:bg-rose-50 dark:hover:bg-rose-500/15 transition-colors"
                >
                  <Trash2 className="w-3 h-3" />
                  {t('shifts.autoGen.existing.clear')}
                </button>
              )}
            </div>
          )}
        </div>

        <div className="p-6 bg-slate-50 dark:bg-slate-800/40 border-t border-slate-100 dark:border-slate-700/60 flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-6 py-2 rounded text-sm font-bold text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700 transition-all uppercase tracking-widest"
          >
            {t('action.cancel')}
          </button>
          {tab === 'gaps' ? (
            <button
              onClick={handleApply}
              disabled={hasNoDemand || isAdequate}
              className={cn(
                'px-6 py-2 rounded text-sm font-bold transition-all shadow-lg uppercase tracking-widest',
                hasNoDemand || isAdequate
                  ? 'bg-slate-200 dark:bg-slate-700 text-slate-400 dark:text-slate-500 cursor-not-allowed'
                  : 'bg-gradient-to-r from-violet-600 to-blue-600 text-white hover:from-violet-700 hover:to-blue-700',
              )}
            >
              {isAdequate
                ? t('shifts.autoGen.applyAdequate')
                : t('shifts.autoGen.apply', { count: generated.length })}
            </button>
          ) : (
            // v5.19.2 — Adopt-and-replace primary action. Disabled when
            // there's nothing to change OR when the parent didn't
            // pass an onReplaceLibrary handler. Confirmation lives in
            // the parent (App.tsx wraps the call with the standard
            // confirmation modal).
            <button
              onClick={handleAdopt}
              disabled={hasNoDemand || optimizeUnchanged || !onReplaceLibrary}
              className={cn(
                'px-6 py-2 rounded text-sm font-bold transition-all shadow-lg uppercase tracking-widest',
                hasNoDemand || optimizeUnchanged || !onReplaceLibrary
                  ? 'bg-slate-200 dark:bg-slate-700 text-slate-400 dark:text-slate-500 cursor-not-allowed'
                  : 'bg-gradient-to-r from-emerald-600 to-blue-600 text-white hover:from-emerald-700 hover:to-blue-700',
              )}
            >
              {optimizeUnchanged
                ? t('shifts.autoGen.optimize.unchangedAction')
                : t('shifts.autoGen.optimize.adopt', {
                    add: proposal?.toAdd.length ?? 0,
                    del: proposal?.toDelete.length ?? 0,
                  })}
            </button>
          )}
        </div>
      </motion.div>
    </div>
  );
}

// v5.19.2 — Optimize tab body. Renders the alternative-library
// proposal: a green headline summarising the migration, a delta-tile
// row, two side-by-side columns (Current → Proposed) with shifts
// flagged add / keep / delete, and a fixed-issues block when the
// proposal eliminates problems with the current library.
function OptimizeView({
  proposal,
  unchanged,
}: {
  proposal: ReturnType<typeof buildOptimizationProposal>;
  unchanged: boolean;
}) {
  const { t } = useI18n();
  const fmtH = (n: number) => `${n.toFixed(1)}h`;

  if (unchanged) {
    return (
      <div className="p-5 rounded-lg border border-emerald-200 dark:border-emerald-500/40 bg-emerald-50 dark:bg-emerald-500/10 flex items-start gap-3">
        <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-300 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-[11px] font-black text-emerald-700 dark:text-emerald-200 uppercase tracking-widest">
            {t('shifts.autoGen.optimize.unchanged.title')}
          </p>
          <p className="text-[11px] text-slate-600 dark:text-slate-300 leading-relaxed">
            {t('shifts.autoGen.optimize.unchanged.body')}
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Headline summary */}
      <div className="p-4 rounded-lg border border-emerald-200 dark:border-emerald-500/40 bg-emerald-50 dark:bg-emerald-500/10 flex items-start gap-3">
        <Wand2 className="w-5 h-5 text-emerald-600 dark:text-emerald-300 shrink-0 mt-0.5" />
        <div className="min-w-0 flex-1 space-y-1">
          <p className="text-[11px] font-black text-emerald-700 dark:text-emerald-200 uppercase tracking-widest">
            {t('shifts.autoGen.optimize.headline.title')}
          </p>
          <p className="text-[11px] text-slate-700 dark:text-slate-200 leading-relaxed">
            {proposal.summary}
          </p>
        </div>
      </div>

      {/* Delta tiles. Four key metrics: shift count change, fixed
          over-cap count, fixed redundancy count, average shift
          duration before → after. */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        <DeltaTile
          label={t('shifts.autoGen.optimize.delta.shiftCount')}
          before={proposal.currentWorkShifts.length}
          after={proposal.proposedLibrary.length}
        />
        <DeltaTile
          label={t('shifts.autoGen.optimize.delta.avgDuration')}
          beforeText={fmtH(proposal.delta.currentAvgDuration)}
          afterText={fmtH(proposal.delta.proposedAvgDuration)}
        />
        <DeltaTile
          label={t('shifts.autoGen.optimize.delta.overCapFixed')}
          before={proposal.delta.fixedOverCap}
          after={0}
          tone="rose-to-emerald"
        />
        <DeltaTile
          label={t('shifts.autoGen.optimize.delta.redundantFixed')}
          before={proposal.delta.fixedRedundant + proposal.delta.fixedSubsumed}
          after={0}
          tone="rose-to-emerald"
        />
      </div>

      {/* Side-by-side: Current → Proposed */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
        <ShiftListColumn
          title={t('shifts.autoGen.optimize.current.title', { count: proposal.currentWorkShifts.length })}
          subtitle={t('shifts.autoGen.optimize.current.subtitle')}
          tone="slate"
          entries={[
            ...proposal.toDelete.map(d => ({ ...d, badge: 'delete' as const })),
            ...proposal.toKeep.map(k => ({ ...k, badge: 'keep' as const })),
          ]}
        />
        <ShiftListColumn
          title={t('shifts.autoGen.optimize.proposed.title', { count: proposal.proposedLibrary.length })}
          subtitle={t('shifts.autoGen.optimize.proposed.subtitle')}
          tone="emerald"
          entries={[
            ...proposal.toKeep.map(k => ({ ...k, badge: 'keep' as const })),
            ...proposal.toAdd.map(a => ({ ...a, badge: 'add' as const })),
          ]}
        />
      </div>

      {/* Fixed issues callout — what the migration eliminates */}
      {proposal.fixedIssues.length > 0 && (
        <div className="p-3 rounded-lg border border-blue-200 dark:border-blue-500/30 bg-blue-50 dark:bg-blue-500/10 space-y-1.5">
          <p className="text-[10px] font-black text-blue-800 dark:text-blue-200 uppercase tracking-widest">
            {t('shifts.autoGen.optimize.fixed.title', { count: proposal.fixedIssues.length })}
          </p>
          <ul className="space-y-1 text-[10px] text-blue-700 dark:text-blue-200">
            {proposal.fixedIssues.map((iss, i) => (
              <li key={i} className="leading-relaxed">
                <span className="px-1.5 py-0.5 me-1 rounded font-mono font-black uppercase tracking-widest text-[8px] bg-blue-100 dark:bg-blue-500/20 border border-blue-200 dark:border-blue-500/40">
                  {t(`shifts.autoGen.issues.kind.${iss.kind}`)}
                </span>
                {iss.message}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Coverage equivalence sanity-check — should always be true. */}
      {!proposal.delta.coverageEquivalent && (
        <div className="p-3 rounded-lg border border-amber-200 dark:border-amber-500/40 bg-amber-50 dark:bg-amber-500/10 text-[10px] text-amber-800 dark:text-amber-200">
          {t('shifts.autoGen.optimize.coverageWarning')}
        </div>
      )}
    </div>
  );
}

function DeltaTile({
  label, before, after, beforeText, afterText, tone,
}: {
  label: string;
  before?: number;
  after?: number;
  beforeText?: string;
  afterText?: string;
  tone?: 'rose-to-emerald';
}) {
  const beforeStr = beforeText ?? (before ?? 0).toString();
  const afterStr = afterText ?? (after ?? 0).toString();
  const isImprovement = tone === 'rose-to-emerald'
    ? (before ?? 0) > (after ?? 0)
    : false;
  return (
    <div className={cn(
      'p-2.5 rounded-lg border',
      isImprovement
        ? 'border-emerald-200 dark:border-emerald-500/30 bg-emerald-50/40 dark:bg-emerald-500/10'
        : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40',
    )}>
      <p className="text-[8px] font-black uppercase tracking-widest text-slate-500 dark:text-slate-400 mb-1">{label}</p>
      <p className="text-xs font-mono">
        <span className="text-slate-500 dark:text-slate-400">{beforeStr}</span>
        <ArrowRight className="inline w-3 h-3 mx-1 text-slate-400 dark:text-slate-500" />
        <span className={cn('font-black', isImprovement ? 'text-emerald-700 dark:text-emerald-200' : 'text-slate-800 dark:text-slate-100')}>{afterStr}</span>
      </p>
    </div>
  );
}

function ShiftListColumn({
  title, subtitle, tone, entries,
}: {
  title: string;
  subtitle: string;
  tone: 'slate' | 'emerald';
  entries: Array<{ shift: Shift; reason: string; badge: 'add' | 'delete' | 'keep' }>;
}) {
  const { t } = useI18n();
  const headerTone = tone === 'emerald'
    ? 'bg-emerald-50/40 dark:bg-emerald-500/10 border-emerald-200 dark:border-emerald-500/30'
    : 'bg-slate-50 dark:bg-slate-800/40 border-slate-200 dark:border-slate-700';
  return (
    <div className={cn('rounded-lg border overflow-hidden', headerTone)}>
      <div className="px-3 py-2 border-b border-slate-200 dark:border-slate-700/60">
        <p className="text-[10px] font-black uppercase tracking-widest text-slate-700 dark:text-slate-200">{title}</p>
        <p className="text-[9px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">{subtitle}</p>
      </div>
      <div className="divide-y divide-slate-200 dark:divide-slate-700/60 max-h-[36vh] overflow-y-auto">
        {entries.length === 0 ? (
          <p className="text-[10px] text-slate-400 dark:text-slate-500 italic p-3">—</p>
        ) : (
          entries.map((e, i) => {
            const badgeTone =
              e.badge === 'add' ? 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-700 dark:text-emerald-200 border-emerald-200 dark:border-emerald-500/40'
              : e.badge === 'delete' ? 'bg-rose-100 dark:bg-rose-500/20 text-rose-700 dark:text-rose-200 border-rose-200 dark:border-rose-500/40'
              : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-700';
            const BadgeIcon = e.badge === 'add' ? Plus : e.badge === 'delete' ? Minus : CheckCircle2;
            return (
              <div key={`${e.shift.code}-${i}`} className="p-3 bg-white dark:bg-slate-900/30 flex items-start gap-2">
                <span className={cn('shrink-0 px-1.5 py-0.5 rounded border text-[8px] font-black uppercase tracking-widest flex items-center gap-1', badgeTone)}>
                  <BadgeIcon className="w-2.5 h-2.5" />
                  {t(`shifts.autoGen.optimize.badge.${e.badge}`)}
                </span>
                <div className="min-w-0 flex-1">
                  <p className="text-[11px] font-bold text-slate-800 dark:text-slate-100 truncate">
                    <span className="font-mono text-violet-700 dark:text-violet-200 me-1.5">{e.shift.code}</span>
                    {e.shift.name}
                  </p>
                  <p className="text-[9px] text-slate-500 dark:text-slate-400 font-mono">
                    {e.shift.start}–{e.shift.end} · {e.shift.durationHrs}h
                  </p>
                  <p className="text-[10px] text-slate-600 dark:text-slate-300 mt-1 leading-relaxed">{e.reason}</p>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
