import { describe, expect, it } from 'vitest';
import { generateOptimalShifts } from '../shiftGenerator';
import type { Config, Shift, Station } from '../../types';

const baseConfig = (): Config => ({
  company: 'Test',
  year: 2026, month: 5, daysInMonth: 31,
  weekendPolicy: 'fri-sat',
  weeklyRestDayPrimary: 6,
  continuousShiftsMode: 'OFF',
  coverageMin: 1,
  maxConsecWorkDays: 6,
  standardDailyHrsCap: 8,
  hazardousDailyHrsCap: 6,
  standardWeeklyHrsCap: 48,
  hazardousWeeklyHrsCap: 36,
  minRestBetweenShiftsHrs: 11,
  shopOpeningTime: '11:00',
  shopClosingTime: '23:00',
  peakDays: [5, 6, 7],
  otRateDay: 1.5,
  otRateNight: 2.0,
});

const station = (over: Partial<Station>): Station => ({
  id: over.id || 's1',
  name: over.name || 'Cashier 1',
  normalMinHC: 1,
  peakMinHC: 2,
  openingTime: '11:00',
  closingTime: '23:00',
  ...over,
});

describe('generateOptimalShifts', () => {
  it('returns empty when no stations supplied', () => {
    const result = generateOptimalShifts([], baseConfig(), []);
    expect(result.generated).toHaveLength(0);
    expect(result.notes).toContain('no-demand');
    expect(result.verdict).toBe('no-demand');
  });

  it('generates a single anchor shift for a window <= daily cap', () => {
    const stations = [station({ openingTime: '13:00', closingTime: '20:00', normalMinHC: 1, peakMinHC: 2 })];
    const result = generateOptimalShifts(stations, baseConfig(), []);
    expect(result.generated).toHaveLength(1);
    expect(result.generated[0].start).toBe('13:00');
    expect(result.generated[0].end).toBe('20:00');
    expect(result.generated[0].durationHrs).toBe(7);
    expect(result.generated[0].autoGenerated).toBe(true);
  });

  it('generates two staggered shifts for a 12h window with 8h daily cap', () => {
    const stations = [station({ openingTime: '11:00', closingTime: '23:00', normalMinHC: 1, peakMinHC: 3 })];
    const result = generateOptimalShifts(stations, baseConfig(), []);
    expect(result.generated).toHaveLength(2);
    expect(result.generated[0].start).toBe('11:00');
    expect(result.generated[0].end).toBe('19:00');
    expect(result.generated[1].start).toBe('15:00');
    expect(result.generated[1].end).toBe('23:00');
  });

  it('caps every generated shift at the daily cap', () => {
    const stations = [station({ openingTime: '06:00', closingTime: '23:00', normalMinHC: 2, peakMinHC: 4 })];
    const result = generateOptimalShifts(stations, baseConfig(), []);
    expect(result.generated.length).toBeGreaterThanOrEqual(2);
    for (const s of result.generated) {
      expect(s.durationHrs).toBeLessThanOrEqual(8);
    }
  });

  it('avoids code collisions with existing shifts', () => {
    const stations = [station({})];
    const existing: Shift[] = [{
      code: 'AG1', name: 'Reserved', start: '09:00', end: '17:00',
      durationHrs: 8, breakMin: 60, isIndustrial: false, isHazardous: false, isWork: true, description: '',
    }];
    const result = generateOptimalShifts(stations, baseConfig(), existing);
    expect(result.generated.find(s => s.code === 'AG1')).toBeUndefined();
    expect(result.generated.length).toBeGreaterThan(0);
    for (const s of result.generated) {
      expect(s.code).not.toBe('AG1');
    }
  });

  it('records max peak HC across each shift span', () => {
    const stations = [
      station({ id: 'a', openingTime: '11:00', closingTime: '15:00', peakMinHC: 2, normalMinHC: 1 }),
      station({ id: 'b', openingTime: '15:00', closingTime: '19:00', peakMinHC: 5, normalMinHC: 2 }),
    ];
    const result = generateOptimalShifts(stations, baseConfig(), []);
    expect(result.demandProfile.peakByHour[12]).toBe(2);
    expect(result.demandProfile.peakByHour[16]).toBe(5);
    expect(result.suggestions.some(s => s.recommendedPeakHC >= 5)).toBe(true);
  });

  it('respects hourly demand profiles when present', () => {
    const stations: Station[] = [{
      id: 's1', name: 'Var Cashier',
      normalMinHC: 0, peakMinHC: 0,
      openingTime: '11:00', closingTime: '23:00',
      normalHourlyDemand: [
        { startHour: 11, endHour: 15, hc: 1 },
        { startHour: 15, endHour: 19, hc: 2 },
        { startHour: 19, endHour: 23, hc: 3 },
      ],
      peakHourlyDemand: [
        { startHour: 11, endHour: 15, hc: 2 },
        { startHour: 15, endHour: 19, hc: 4 },
        { startHour: 19, endHour: 23, hc: 5 },
      ],
    }];
    const result = generateOptimalShifts(stations, baseConfig(), []);
    expect(result.demandProfile.peakByHour[12]).toBe(2);
    expect(result.demandProfile.peakByHour[16]).toBe(4);
    expect(result.demandProfile.peakByHour[20]).toBe(5);
    expect(result.generated.length).toBeGreaterThan(0);
    for (const s of result.generated) {
      expect(s.autoGenerated).toBe(true);
    }
  });

  // v5.19.0 — gap-aware regeneration. Running the generator a second
  // time with the previously-generated shifts already in the library
  // should NOT duplicate them.
  it('returns verdict=adequate and zero new shifts when existing library covers all demand', () => {
    const stations = [station({ openingTime: '13:00', closingTime: '20:00', normalMinHC: 1, peakMinHC: 2 })];
    const firstPass = generateOptimalShifts(stations, baseConfig(), []);
    expect(firstPass.generated.length).toBeGreaterThan(0);
    expect(firstPass.verdict).toBe('no-coverage');

    // Second pass: feed the first-pass output back as the existing library.
    const secondPass = generateOptimalShifts(stations, baseConfig(), firstPass.generated);
    expect(secondPass.generated).toHaveLength(0);
    expect(secondPass.verdict).toBe('adequate');
    expect(secondPass.notes).toContain('adequate-coverage');
    expect(secondPass.existingCoverage.pctCovered).toBe(100);
    expect(secondPass.existingCoverage.uncoveredHours).toBe(0);
  });

  it('returns verdict=partial and only fills uncovered windows', () => {
    // Station open 11–23. Existing library only covers 11–19 → 19–23 is a gap.
    const stations = [station({ openingTime: '11:00', closingTime: '23:00', normalMinHC: 1, peakMinHC: 2 })];
    const existing: Shift[] = [{
      code: 'M', name: 'Morning', start: '11:00', end: '19:00',
      durationHrs: 8, breakMin: 60, isIndustrial: false, isHazardous: false, isWork: true, description: '',
    }];
    const result = generateOptimalShifts(stations, baseConfig(), existing);
    expect(result.verdict).toBe('partial');
    expect(result.existingCoverage.coveredHours).toBe(8);   // 11..18 inclusive
    expect(result.existingCoverage.uncoveredHours).toBe(4); // 19..22 inclusive
    expect(result.generated.length).toBeGreaterThan(0);
    // Every generated shift should fall inside the gap window.
    for (const s of result.generated) {
      const startH = parseInt(s.start.split(':')[0], 10);
      expect(startH).toBeGreaterThanOrEqual(19);
    }
  });

  it('skips system shifts (OFF/AL/SL/MAT/PH/CP) when computing existing coverage', () => {
    // System shifts cover no real floor time even though their hours
    // could parse. Generator should still propose shifts as if the
    // library were empty.
    const stations = [station({ openingTime: '11:00', closingTime: '15:00', normalMinHC: 1, peakMinHC: 2 })];
    const existing: Shift[] = [{
      code: 'OFF', name: 'Off', start: '11:00', end: '15:00',
      durationHrs: 4, breakMin: 0, isIndustrial: false, isHazardous: false, isWork: false, description: '',
    }];
    const result = generateOptimalShifts(stations, baseConfig(), existing);
    expect(result.verdict).toBe('no-coverage');
    expect(result.generated.length).toBeGreaterThan(0);
  });

  it('emits separate shift sets for disjoint open windows', () => {
    const stations: Station[] = [{
      id: 's1', name: 'Split',
      normalMinHC: 0, peakMinHC: 0,
      openingTime: '06:00', closingTime: '23:00',
      peakHourlyDemand: [
        { startHour: 6, endHour: 9, hc: 1 },
        { startHour: 17, endHour: 22, hc: 2 },
      ],
      normalHourlyDemand: [
        { startHour: 6, endHour: 9, hc: 1 },
        { startHour: 17, endHour: 22, hc: 1 },
      ],
    }];
    const result = generateOptimalShifts(stations, baseConfig(), []);
    expect(result.generated).toHaveLength(2);
    expect(result.generated[0].start).toBe('06:00');
    expect(result.generated[0].end).toBe('09:00');
    expect(result.generated[1].start).toBe('17:00');
    expect(result.generated[1].end).toBe('22:00');
  });
});
